# ---
# The make file who contain all variables
# ---
include Makefile.cfg

# ---
# Tools variable
# ---

MKDIR := mkdir
RM := rm
ECHO := /usr/bin/echo

# ---
# Docker variable
# ---

IMAGE_NAME := pestilence
CONTAINER_NAME := pestilence_container
DOCKERFILE := Dockerfile
DOCKER_BUILD_CONTEXT := .

# ---
# Build variables
# ---

# Compiler

CC := gcc

CWARN := all extra error
CWARN := $(CWARN:%=-W%)

CFLAGS := $(if $(filter $(ARCH),64),,-m32) -MMD $(CWARN) -std=c23 -fPIE $(if $(OPTIMIZE),-O3,) $(if $(DEBUG),-g,) \
	$(if $(DEBUG),-DDEBUG,) $(CMOREFLAGS) -D_GNU_SOURCE

CFLAGS_STUB := $(CWARN) -std=gnu23 $(if $(DEBUG),-DDEBUG,) -I. -D_STUB_SOURCE -D_GNU_SOURCE

CFLAGS_STUB64 := $(CFLAGS_STUB) \
				-fno-stack-protector -include stub/force_hidden.h -fPIC -ffreestanding -fvisibility=hidden -nostdlib -static -fno-semantic-interposition
CFLAGS_STUB32 := $(CFLAGS_STUB) -m32 \
				-fno-stack-protector -include stub/force_hidden.h -fPIC -ffreestanding -fvisibility=hidden -nostdlib -static -fno-semantic-interposition

# Linker

LD := gcc

LD_EMUL := $(if $(filter $(ARCH),64),elf_x86_64,elf_i386)
LDFLAGS := $(if $(filter $(ARCH),64),,-m32) -pie $(LDMOREFLAGS)
LD_LIBS :=

# Assembler

AS := as

ASFLAGS := $(if $(filter $(ARCH),64),,--32)

# ---
# Library dependencies
# ---

THIRDPARTY := thirdparty

LIBS :=

LIBS_MAKE_RULE :=
LIBS_CLEAN_RULE :=
LIBS_FCLEAN_RULE :=

define get-lib-info
include $(THIRDPARTY)/$1.dep
LD_LIBS += $$(LIBA_$1:lib%.a=-l%) $$(DEP_LD_LIBS_$1)
CFLAGS += -I$(THIRDPARTY)/$$(INCDIR_$1)
LDFLAGS += -L$(THIRDPARTY)/$$(LIBDIR_$1)
LIBS_MAKE_RULE += MAKE_RULE_$1
LIBS_CLEAN_RULE += CLEAN_RULE_$1
LIBS_FCLEAN_RULE += FCLEAN_RULE_$1
endef

$(foreach lib,$(LIBS),$(eval $(call get-lib-info,$(lib))))

# ---
# Source/binary information
# ---

# Binary

BIN := pestilence
BIN_PATH := $(OUTDIR)/$(BIN)

SRCDIR := src
INCDIR := include

CFLAGS += -I$(INCDIR) -I.

SRCS := $(wildcard $(SRCDIR)/*.c) $(wildcard $(SRCDIR)/**/*.c)
OBJS := $(SRCS:$(SRCDIR)/%.c=$(OBJDIR)/%.c.o)
DEPS := $(OBJS:%.c.o=%.c.d)
OBJS += $(if $(filter $(ARCH),64),$(OBJDIR)/xtea_crypt_64.S.o,$(OBJDIR)/xtea_crypt_32.S.o)
OBJS += $(if $(filter $(ARCH),64),$(OBJDIR)/pestilence_64.c.o,$(OBJDIR)/pestilence_32.c.o)

# ---
# Resources
# ---

RESDIR := resources
RESOURCES := $(RESDIR)/stub64.bin $(RESDIR)/stub32.bin $(RESDIR)/packer64.bin $(RESDIR)/packer32.bin
OBJS += $(RESOURCES:$(RESDIR)/%=$(OBJDIR)/%.res.o)
